---
title: '***PROPOSED BUDGET: Data Analytics: Analyzing and Visualizing Data with Excel Training***'
author: "John Karuitha"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(kableExtra)
```


```{r}
tribble(~ Description, ~ Note , ~ Amount,
        
        "Training Fees", "1", "72,000.00",
        
        "Per Diem", "2", "56,000.00",
        
        "Transport" , "3", "Self Catered - Ksh 10,000.00",
        
        "TOTAL", "", "128,000.00") %>% 
        
        kbl(., booktabs = TRUE, caption = "Proposed Budget to Attend ISACA Data Analysis With Excel Training") %>% 
        
        kable_classic(latex_options = "hold_position", 
                      
                      full_width = TRUE) %>% 
        add_footnote(label = c("See attached conference schedule", "Five Days at City rate of 11,200.00 per day", "Self Catered transport"), notation = "number")
```

